name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run ruff check
        # For example, using `pytest`
        run: uv run ruff check .
      - name: Run ruff format check
        # For example, using `pytest`
        run: uv run ruff format --check
      - name: Normalize Lua data
        run: uv run tools/normalize.py
      - name: Check for changes
        run: git diff --exit-code